update bash_sonia script

diff --git a/docs/assets/files/melodic_18.04/bash_sonia b/docs/assets/files/melodic_18.04/bash_sonia
--- a/docs/assets/files/melodic_18.04/bash_sonia
+++ b/docs/assets/files/melodic_18.04/bash_sonia
@@ -10,6 +10,7 @@ export ROS_HOME=$ROS_SONIA_WS
 export ROS_IP=${IP_ADDRESS}
 export LC_ALL="en_US.UTF-8"
 export EDITOR="vim"
+export SONIA_ENVIRONMENT=devel
 export ROS_MAVEN_DEPLOYMENT_REPOSITORY=$HOME/.m2/repository/
 
 ## ROS specific configurations
@@ -21,7 +22,10 @@ fi
 ## Useful aliases
 alias sas='roslaunch ${ROS_SONIA_WS}/launch/simulation_auv7.launch'
 alias babe='ssh -X sonia@192.168.0.11'
+alias jetson='ssh -X nvidia@192.168.0.13'
 alias babe?='ping 192.168.0.11'
+alias switch?='ping 192.168.0.12'
+alias jetson?='ping 192.168.0.13'
 alias sonia-source='source ${ROS_SONIA_WS}/devel/setup.bash'
 alias sonia-cd='cd ${ROS_SONIA_WS} && sonia-source'
 alias sonia-wakeup='wol 00:30:18:b0:3d:f4'
@@ -36,6 +40,11 @@ function comp () {
     cd ${ROS_SONIA_WS}
     catkin_make -j8 -DCMAKE_CXX_FLAGS="-O2"
     cd -
+}
+
+function full_poof () {
+    ssh sonia@192.168.0.11 "source /etc/profile; poof"
+    ssh nvidia@192.168.0.13 "source /etc/profile; poof"
 }
 
 function comp_reset () {
@@ -56,6 +65,13 @@ function swap_babe () {
 }
 
 function update-sonia-script () {
-    wget http://sonia-auv.readthedocs.org/assets/files/melodic_18.04/bash_sonia -O ~/.bash_sonia
-    source ~/.bash_sonia
+
+    ping -c1 readthedocs.org 2>/dev/null 1>/dev/null
+    if [ "$?" = 0 ]
+    then
+        wget http://sonia-auv.readthedocs.org/assets/files/melodic_18.04/bash_sonia_dev -O ~/.bash_sonia
+        source ~/.bash_sonia
+    else
+        echo "Host not found"
+    fi
 }
