add protection to update-sonia-script

diff --git a/docs/assets/files/ugnome_16.04/bash_sonia_dev b/docs/assets/files/ugnome_16.04/bash_sonia_dev
--- a/docs/assets/files/ugnome_16.04/bash_sonia_dev
+++ b/docs/assets/files/ugnome_16.04/bash_sonia_dev
@@ -71,6 +71,13 @@ function swap_babe () {
 }
 
 function update-sonia-script () {
-    wget http://sonia-auv.readthedocs.org/assets/files/ugnome_16.04/bash_sonia_dev -O ~/.bash_sonia
-    source ~/.bash_sonia
+
+    ping -c1 readthedocs.org 2>/dev/null 1>/dev/null
+    if [ "$?" = 0 ]
+    then
+        wget http://sonia-auv.readthedocs.org/assets/files/ugnome_16.04/bash_sonia_dev -O ~/.bash_sonia
+        source ~/.bash_sonia
+    else
+        echo "Host not found"
+    fi
 }
